auth-server:
   build: OAuthServer
   ports:
      - 9999:9999
   links:
      - database      

wallet-service:
   build: Wallet
   ports:
      - 6000:5000
   links:
      - database
      - auth-server
      
database:
   image: postgres:9.5
   environment:
     - POSTGRES_PASSWORD=mysecretpassword
   ports:
      - 5432:5432
      
