server:
  port: 9999
security:
    oauth2:
        client:
            client-id: Unicef-Norway
            client-secret: lgUnicef
            authorized-grant-types: authorization_code,refresh_token,password
            scope: wallet, write,read
            client-authentication-scheme: header
            authorities: ROLE_CLIENT, ROLE_TRUSTED_CLIENT
            resource-ids: wallet
            access-token-validity-seconds: 900
            refresh-token-validity-seconds: 3600
    basic:
      enabled: false

spring:
  application:
    name: Auth-Server
  datasource:
      username: postgres
      password: telerin
      url: jdbc:postgresql://localhost:5432/users
      data-source-class-name: org.postgresql.ds.PGPoolingDataSource
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

#
#
#eureka:
#    client:
#      service-url:
#        defaultZone: http://${EUREKA_SERVER}:8761/eureka/
#      enabled: false
#    instance:
#        prefer-ip-address: true
#        status-page-url-path: ${management.context-path}/info
logging:
  level:
    org.springframework.security: DEBUG


endpoints:
  beans:
    enabled: true
  autoconfig:
    enabled: true




